name: Plan Version Bump

on:
  push:
    branches:
      - main

concurrency:
  group: plan-bump
  cancel-in-progress: true

jobs:
  plan-version-bump:
    name: Plan Version Bump
    runs-on: ubuntu-latest
    container: discourse/discourse_test:slim
    timeout-minutes: 5
    permissions:
      contents: write
      issues: read
      pull-requests: write
    steps:
      - name: Set working directory owner
        run: chown root:root .
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'main'
      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"
      - name: Symlink vendor/bundle from image
        run: |
          ln -s /var/www/discourse/vendor/bundle vendor/bundle
      - name: "Bundle install"
        run: bundle install
      - name: "Plan Version Bump"
        run: DRY_RUN=1 bin/rake version_bump:beta
      - name: Checkout new branch
        run: git checkout -b version_bump/beta
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: version_bump/beta
          title: Prepare beta version bump
          draft: true
          body: |
            Testing 123
