
name: Version Bump Helper

on:
  pull_request:
    types: [ready_for_review]
    paths: ['lib/version.rb']
  issue_comment:
    types: [created]

concurrency:
  group: plan-bump
  cancel-in-progress: true

jobs:
  force-draft:
    if: github.event_name == 'pull_request' && github.head_ref == 'version_bump/beta' && github.event.action == 'ready_for_review'
    name: force draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Set to draft"
        run: gh pr ready ${{ github.event.number }} --undo --repo ${{ github.repository }}
      - name: "Post comment"
        run: gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} -b "Do not use the GitHub UI to merge this PR. When ready to perform the version bump, approve the PR, and make a comment with the text '@discoursebot merge version bump'"

  echo:
    name: echo
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "${{toJSON(github.event)}}"

  trigger-version-bump:
    if: | 
      github.event_name == 'issue_comment' &&
        github.event.action == 'created' &&
        github.event.issue.pull_request &&
        github.event.comment.body == '@discoursebot merge version bump' &&
        (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER')
    name: trigger version bump
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Post comment"
        run: gh pr comment ${{ github.event.issue.number }} --repo ${{ github.repository }} -b "Starting merge..."
